export {
  VIFU_HOST_SOURCE,
  VIFU_IOS_HOST_SOURCE,
  VIFU_PROTOCOL_VERSION,
  VIFU_RUNTIME_CAPABILITY,
  VIFU_RUNTIME_CONNECT_MESSAGE,
  VIFU_RUNTIME_METHODS,
  VIFU_RUNTIME_SOURCE,
  VIFU_SDK_VERSION,
  VIFU_WEB_HOST_SOURCE,
} from "./constants.js";
export { createClient, createGameRuntimeSDK, createVifuSDK } from "./sdk.js";
