export const JSON_RPC_ERROR_CODES = {
  PARSE_ERROR: -32700,
  INVALID_REQUEST: -32600,
  METHOD_NOT_FOUND: -32601,
  INVALID_PARAMS: -32602,
  INTERNAL_ERROR: -32603,
} as const;

export const VIFU_PROJECT_RPC_ERROR_CODES = {
  AGENT_GATEWAY_UNAVAILABLE: -32001,
  AGENT_GATEWAY_BUSY: -32002,
  AGENT_REQUEST_TIMED_OUT: -32003,
  AGENT_REQUEST_FAILED: -32004,
} as const;

export type JsonRpcErrorCode =
  (typeof JSON_RPC_ERROR_CODES)[keyof typeof JSON_RPC_ERROR_CODES];

export type VifuProjectRpcErrorCode =
  (typeof VIFU_PROJECT_RPC_ERROR_CODES)[keyof typeof VIFU_PROJECT_RPC_ERROR_CODES];
