[package]
name = "vifu-game-runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Composable Bevy headless runtime primitives for Vifu."
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
bevy_app.workspace = true
bevy_ecs.workspace = true
serde.workspace = true
serde_json.workspace = true
